## *********************************************************
## 
## File autogenerated for the cob_3d_mapping_common package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

config_description = [{'srcline': 13, 'description': 'A calibration parameter for field of view: horizontal angle in degree', 'max': 360.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/field_of_view.cfg', 'name': 'sensor_fov_hor_angle', 'edit_method': '', 'default': 80.0, 'level': 0, 'min': 0.0, 'type': 'double'}, {'srcline': 14, 'description': 'A calibration parameter for field of view: vertical angle in degree', 'max': 360.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/field_of_view.cfg', 'name': 'sensor_fov_ver_angle', 'edit_method': '', 'default': 47.0, 'level': 1, 'min': 0.0, 'type': 'double'}, {'srcline': 15, 'description': 'A calibration parameter for field of view: maximum range of sensor', 'max': 'std::numeric_limits<double>::infinity()', 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/field_of_view.cfg', 'name': 'sensor_max_range', 'edit_method': '', 'default': 5.0, 'level': 2, 'min': 0.0, 'type': 'double'}, {'srcline': 16, 'description': 'The camera frame id', 'max': '', 'cconsttype': 'const char * const', 'ctype': 'std::string', 'srcfile': '../cfg/field_of_view.cfg', 'name': 'camera_frame', 'edit_method': '', 'default': 'head_cam3d_link', 'level': 3, 'min': '', 'type': 'str'}]

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

for param in config_description:
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

