(cl:defpackage cob_3d_registration-srv
  (:use )
  (:export
   "REGISTRATIONPCD"
   "<REGISTRATIONPCD-REQUEST>"
   "REGISTRATIONPCD-REQUEST"
   "<REGISTRATIONPCD-RESPONSE>"
   "REGISTRATIONPCD-RESPONSE"
   "EVALUATIONRESULT"
   "<EVALUATIONRESULT-REQUEST>"
   "EVALUATIONRESULT-REQUEST"
   "<EVALUATIONRESULT-RESPONSE>"
   "EVALUATIONRESULT-RESPONSE"
   "PARAMETERLIST"
   "<PARAMETERLIST-REQUEST>"
   "PARAMETERLIST-REQUEST"
   "<PARAMETERLIST-RESPONSE>"
   "PARAMETERLIST-RESPONSE"
   "EVALUATIONASSUMPTIONS"
   "<EVALUATIONASSUMPTIONS-REQUEST>"
   "EVALUATIONASSUMPTIONS-REQUEST"
   "<EVALUATIONASSUMPTIONS-RESPONSE>"
   "EVALUATIONASSUMPTIONS-RESPONSE"
  ))

